export const copy = {
  es: {
    skip: 'Saltar al contenido',
    nav: [
      'Inicio',
      'El Observatorio',
      'EUROACE Analytics',
      'Publicaciones',
      'Actualidad',
      'Eventos',
      'Contacto',
    ],
    eyebrow: 'OBSERVATORIO DE COOPERACIÓN TRANSFRONTERIZA',
    title: ['Tres regiones.', 'Un horizonte', 'compartido.'],
    intro:
      'Conocimiento que conecta Extremadura, Alentejo y Centro de Portugal. Investigamos el territorio para comprender sus retos y abrir nuevas oportunidades.',
    discover: 'Conoce el Observatorio',
    explore: 'Descubre EUROACE Analytics',
    region: 'UNA EURORREGIÓN, MUCHAS CONEXIONES',
    cooperation: 'Cooperación que se convierte en conocimiento',
    territoryNote: 'Esquema de conexión territorial',
    countries: 'países',
    regions: 'regiones',
    partners: 'socios',
    goal: 'objetivo común',
    goalText: 'Conocer para avanzar',
    aboutLabel: '01 / EL OBSERVATORIO',
    aboutTitle: 'Entender el territorio.\nConectar su potencial.',
    about:
      'Un espacio de conocimiento sobre la EUROACE al servicio de quienes viven, investigan, emprenden y toman decisiones en ella.',
    audience: ['Investigación', 'Empresas', 'Administraciones', 'Ciudadanía'],
    areasLabel: 'ÁREAS DE CONOCIMIENTO',
    areas: [
      'Emprendimiento e innovación',
      'Competitividad',
      'Economía',
      'Energía',
    ],
    areaText: [
      'Ideas y nuevas iniciativas para el territorio.',
      'Capacidades y oportunidades del tejido productivo.',
      'Una mirada compartida al desarrollo regional.',
      'Recursos y transición hacia un futuro sostenible.',
    ],
    analyticsLabel: '02 / EUROACE ANALYTICS',
    analyticsTitle: 'El territorio,\na través de los datos.',
    analyticsText:
      'Una futura plataforma para explorar indicadores, comparar regiones y comprender cómo evoluciona la EUROACE.',
    capabilities: [
      'Indicadores y gráficos',
      'Comparativas territoriales',
      'Mapas y evolución temporal',
    ],
    future: 'EN DESARROLLO',
    preview: 'Vista conceptual · datos ilustrativos',
    index: 'Evolución del indicador',
    units: 'Índice ilustrativo · sin valor estadístico',
    chartAlt:
      'Gráfico conceptual de tres series. Los valores son ficticios y no representan estadísticas de las regiones.',
    publicationsLabel: '03 / PUBLICACIONES',
    publicationsTitle: 'Conocimiento para compartir.',
    publicationsText:
      'Estudios, informes y recursos para acercar la investigación al territorio.',
    formats: ['INFORMES', 'BARÓMETROS', 'INFOGRAFÍAS'],
    pubTitles: [
      'Una mirada al territorio',
      'El pulso de la EUROACE',
      'Datos que se entienden',
    ],
    pubDescriptions: [
      'Análisis de los retos y oportunidades de la eurorregión.',
      'Seguimiento de las dinámicas económicas y empresariales.',
      'Conocimiento visual, accesible y fácil de compartir.',
    ],
    planned: 'Contenido previsto',
    notPublished:
      'Las primeras publicaciones estarán disponibles en este espacio.',
    newsLabel: '04 / ACTUALIDAD Y AGENDA',
    newsTitle: 'Un proyecto en movimiento.',
    news: 'Actualidad',
    newsEmpty: 'Próximamente, novedades del Observatorio',
    newsText:
      'Aquí compartiremos avances de investigación y cooperación entre los socios.',
    events: 'Próximos eventos',
    eventEmpty: 'Una agenda para encontrarnos',
    eventText:
      'Seminarios, encuentros y jornadas. Fechas y programas pendientes de publicación.',
    partnersLabel: 'UNA ALIANZA TRANSFRONTERIZA',
    partnersTitle: 'Cuatro socios. Una visión compartida.',
    junta: 'Dirección General de Acción Exterior',
    juntaName: 'Junta de Extremadura',
    university: 'Universidad de Extremadura',
    partnerNote:
      'Espacio reservado para los logotipos oficiales de los socios.',
    contact: 'Conectemos el conocimiento.',
    contactText:
      'El canal de contacto del Observatorio se publicará próximamente.',
    funding:
      'Proyecto desarrollado en el marco de Interreg VI-A España–Portugal (POCTEP) 2021–2027. Cofinanciado por la Unión Europea.',
    footer: 'Observatorio de Cooperación Transfronteriza EUROACE',
    draft: 'Propuesta de home · contenidos en preparación',
    menu: 'Abrir menú',
    close: 'Cerrar menú',
  },
  pt: {
    skip: 'Saltar para o conteúdo',
    nav: [
      'Início',
      'O Observatório',
      'EUROACE Analytics',
      'Publicações',
      'Atualidade',
      'Eventos',
      'Contacto',
    ],
    eyebrow: 'OBSERVATÓRIO DE COOPERAÇÃO TRANSFRONTEIRIÇA',
    title: ['Três regiões.', 'Um horizonte', 'partilhado.'],
    intro:
      'Conhecimento que liga a Extremadura, o Alentejo e o Centro de Portugal. Investigamos o território para compreender os seus desafios e abrir novas oportunidades.',
    discover: 'Conheça o Observatório',
    explore: 'Descubra o EUROACE Analytics',
    region: 'UMA EURORREGIÃO, MUITAS LIGAÇÕES',
    cooperation: 'Cooperação que se transforma em conhecimento',
    territoryNote: 'Esquema de ligação territorial',
    countries: 'países',
    regions: 'regiões',
    partners: 'parceiros',
    goal: 'objetivo comum',
    goalText: 'Conhecer para avançar',
    aboutLabel: '01 / O OBSERVATÓRIO',
    aboutTitle: 'Compreender o território.\nLigar o seu potencial.',
    about:
      'Um espaço de conhecimento sobre a EUROACE ao serviço de quem nela vive, investiga, empreende e toma decisões.',
    audience: ['Investigação', 'Empresas', 'Administrações', 'Cidadãos'],
    areasLabel: 'ÁREAS DE CONHECIMENTO',
    areas: [
      'Empreendedorismo e inovação',
      'Competitividade',
      'Economia',
      'Energia',
    ],
    areaText: [
      'Ideias e novas iniciativas para o território.',
      'Capacidades e oportunidades do tecido produtivo.',
      'Uma visão partilhada do desenvolvimento regional.',
      'Recursos e transição para um futuro sustentável.',
    ],
    analyticsLabel: '02 / EUROACE ANALYTICS',
    analyticsTitle: 'O território,\natravés dos dados.',
    analyticsText:
      'Uma futura plataforma para explorar indicadores, comparar regiões e compreender a evolução da EUROACE.',
    capabilities: [
      'Indicadores e gráficos',
      'Comparações territoriais',
      'Mapas e evolução temporal',
    ],
    future: 'EM DESENVOLVIMENTO',
    preview: 'Vista conceptual · dados ilustrativos',
    index: 'Evolução do indicador',
    units: 'Índice ilustrativo · sem valor estatístico',
    chartAlt:
      'Gráfico conceptual de três séries. Os valores são fictícios e não representam estatísticas das regiões.',
    publicationsLabel: '03 / PUBLICAÇÕES',
    publicationsTitle: 'Conhecimento para partilhar.',
    publicationsText:
      'Estudos, relatórios e recursos para aproximar a investigação do território.',
    formats: ['RELATÓRIOS', 'BARÓMETROS', 'INFOGRAFIAS'],
    pubTitles: [
      'Um olhar sobre o território',
      'O pulso da EUROACE',
      'Dados que se compreendem',
    ],
    pubDescriptions: [
      'Análise dos desafios e oportunidades da eurorregião.',
      'Acompanhamento das dinâmicas económicas e empresariais.',
      'Conhecimento visual, acessível e fácil de partilhar.',
    ],
    planned: 'Conteúdo previsto',
    notPublished: 'As primeiras publicações estarão disponíveis neste espaço.',
    newsLabel: '04 / ATUALIDADE E AGENDA',
    newsTitle: 'Um projeto em movimento.',
    news: 'Atualidade',
    newsEmpty: 'Em breve, novidades do Observatório',
    newsText:
      'Aqui partilharemos avanços da investigação e da cooperação entre os parceiros.',
    events: 'Próximos eventos',
    eventEmpty: 'Uma agenda para nos encontrarmos',
    eventText:
      'Seminários, encontros e jornadas. Datas e programas a publicar.',
    partnersLabel: 'UMA ALIANÇA TRANSFRONTEIRIÇA',
    partnersTitle: 'Quatro parceiros. Uma visão partilhada.',
    junta: 'Dirección General de Acción Exterior',
    juntaName: 'Junta de Extremadura',
    university: 'Universidad de Extremadura',
    partnerNote: 'Espaço reservado para os logótipos oficiais dos parceiros.',
    contact: 'Vamos ligar o conhecimento.',
    contactText: 'O canal de contacto do Observatório será publicado em breve.',
    funding:
      'Projeto desenvolvido no âmbito do Interreg VI-A Espanha–Portugal (POCTEP) 2021–2027. Cofinanciado pela União Europeia.',
    footer: 'Observatório de Cooperação Transfronteiriça EUROACE',
    draft: 'Proposta de página inicial · conteúdos em preparação',
    menu: 'Abrir menu',
    close: 'Fechar menu',
  },
};
