export const englishCopy = {
  skip: 'Skip to content',
  nav: [
    'Home',
    'The Observatory',
    'EUROACE Analytics',
    'Publications',
    'News',
    'Events',
    'Contact',
  ],
  eyebrow: 'OBSERVATORY FOR CROSS-BORDER COOPERATION',
  title: ['Three regions.', 'One shared', 'horizon'],
  intro:
    'Knowledge connecting Extremadura, Alentejo and Centro in Portugal. We study the region to understand its challenges and explore new opportunities.',
  discover: 'Meet the Observatory',
  explore: 'Discover EUROACE Analytics',
  region: 'ONE EUROREGION, MANY CONNECTIONS',
  cooperation: 'Cooperation that creates knowledge',
  territoryNote: 'Territorial connection diagram',
  countries: 'countries',
  regions: 'regions',
  partners: 'partners',
  goal: 'shared objective',
  goalText: 'Knowledge for progress',
  aboutLabel: 'THE OBSERVATORY',
  aboutTitle: 'Understand the region.\nConnect its potential.',
  about:
    'A knowledge resource about EUROACE for the people who live, research, build businesses and make decisions here.',
  audience: ['Research', 'Businesses', 'Public authorities', 'Citizens'],
  areasLabel: 'KNOWLEDGE AREAS',
  areas: [
    'Entrepreneurship',
    'Innovation and competitiveness',
    'Economy and energy',
  ],
  areaText: [
    'Ideas and new initiatives for the region.',
    'Innovation, capabilities and opportunities for businesses.',
    'Regional development, resources and the energy transition.',
  ],
  analyticsLabel: 'EUROACE ANALYTICS',
  analyticsTitle: 'The region,\nthrough data.',
  analyticsText:
    'A platform in development to explore indicators, compare regions and understand how EUROACE is changing.',
  capabilities: [
    'Indicators and charts',
    'Regional comparisons',
    'Maps and trends over time',
  ],
  future: 'IN DEVELOPMENT',
  preview: 'Concept preview · illustrative data',
  index: 'Indicator trends',
  units: 'Illustrative index · no statistical value',
  chartAlt:
    'Concept chart with three series. These fictional values do not represent regional statistics.',
  publicationsLabel: 'PUBLICATIONS',
  publicationsTitle: 'Knowledge to share.',
  publicationsText:
    'Studies, reports and research resources connecting knowledge with the region.',
  formats: [
    'REPORTS',
    'BAROMETERS',
    'INFOGRAPHICS',
    'RESEARCH ARTICLES',
    'PAPERS',
  ],
  pubTitles: [
    'A view of the region',
    'The pulse of EUROACE',
    'Data made clear',
    'Research to share',
    'Studies and working papers',
  ],
  pubDescriptions: [
    'Analysis of the Euroregion’s challenges and opportunities.',
    'Monitoring economic and business trends.',
    'Visual, accessible knowledge that is easy to share.',
    'Scientific articles produced within the project.',
    'Research findings and working papers.',
  ],
  planned: 'Planned content',
  notPublished: 'The first publications will be available here.',
  newsLabel: 'NEWS',
  newsTitle: 'A project on the move.',
  news: 'News',
  newsEmpty: 'Updates from the Observatory, coming soon',
  newsText:
    'We will share research progress and cooperation between partners here.',
  events: 'Upcoming events',
  eventEmpty: 'An opportunity to meet',
  eventText:
    'Seminars, meetings and workshops. Dates and programmes will be published here.',
  partnersLabel: 'A CROSS-BORDER PARTNERSHIP',
  partnersTitle: 'Four partners. One shared vision.',
  junta: '',
  juntaName: 'Junta de Extremadura',
  university: 'Universidad de Extremadura',
  partnerNote: 'Official partner logos.',
  contact: 'Connect through knowledge.',
  contactText: 'The Observatory’s contact channel will be published soon.',
  funding:
    'Co-funded by the European Union through the Interreg VI-A Spain–Portugal (POCTEP) 2021–2027 Programme.',
  footer: 'EUROACE Observatory for Cross-border Cooperation',
  draft: 'Draft · content under preparation',
  menu: 'Open menu',
  close: 'Close menu',
};
